            - name: Android Sign
  # You may pin to the exact commit or the version.
  # uses: Tlaster/android-sign@1c5bf4b2fa309acb0c0ae0bf9379ab458f14d5b1
  uses: Tlaster/android-sign@v1.2.2
  with:
    # The directory to find your release to sign
    releaseDirectory: 
    # The key used to sign your release in base64 encoded format
    signingKeyBase64: 
    # The key alias
    alias: 
    # The password to the keystore
    keyStorePassword: 
    # The password for the key
    keyPassword: # optional
    # The working directory for action, default to build
    buildDirectory: # optional
    # The output directory for sign, default to build/signed
    output: # optional
          
